version: '3.5'
services:
  mariadb:
    image: mariadb:10.8.3
    container_name: mariadb
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=$DBUSER
      - MARIADB_PASSWORD=$DBPASS
      - MARIADB_ROOT_PASSWORD=$DBROOTPASS
      - MARIADB_DATABASE=$DBNAME
    ports:
      - '3309:3309'
    volumes:
      - '$BASEDIR/data/mariadb:/var/lib/mysql'
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=20480000
      - MAX_EXECUTION_TIME=1200
    ports:
      - '8090:80'
    depends_on:
      - mariadb
      
  frontend:
    image: php:${PHPVER_FRONTEND}-apache-buster
    container_name: www-fe
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - '$BASEDIR/www/frontend:/var/www/html'
    depends_on:
      - mariadb
    links:
      - mariadb
    command: >
      bash -c 
      "apt-get -y update && 
      apt-get -y install libicu-dev && 
      docker-php-ext-configure intl && 
      docker-php-ext-install intl && 
      docker-php-ext-install mysqli && 
      service apache2 restart &&
      php -a"
      
  backend:
    image: php:${PHPVER_BACKEND}-apache-buster
    container_name: www-be
    restart: always
    ports:
      - 8082:80
    volumes:
      - '$BASEDIR/www/backend:/var/www/html'
    depends_on:
      - mariadb
    links:
      - mariadb
    command: >
      bash -c 
      "apt-get -y update && 
      apt-get -y install libicu-dev && 
      docker-php-ext-configure intl && 
      docker-php-ext-install intl && 
      docker-php-ext-install mysqli && 
      service apache2 restart &&
      php -a"
